// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1ffeMe5kNhq_GdpF80IXvP5r5aiGBQRk',
    appId: '1:785935802175:web:b32c138b173324829e3d8a',
    messagingSenderId: '785935802175',
    projectId: 'depi-ecommerce-9e1a8',
    authDomain: 'depi-ecommerce-9e1a8.firebaseapp.com',
    storageBucket: 'depi-ecommerce-9e1a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr-sr2_dPbIRaZ6odfVjinkaqCXaEF9oM',
    appId: '1:785935802175:android:7ab5d678ba48e7369e3d8a',
    messagingSenderId: '785935802175',
    projectId: 'depi-ecommerce-9e1a8',
    storageBucket: 'depi-ecommerce-9e1a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdY8maMRySXTCNtavj4sEl_LcYFCz-zU',
    appId: '1:785935802175:ios:7ee140a99f77a2119e3d8a',
    messagingSenderId: '785935802175',
    projectId: 'depi-ecommerce-9e1a8',
    storageBucket: 'depi-ecommerce-9e1a8.appspot.com',
    iosBundleId: 'com.example.simpleEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUdY8maMRySXTCNtavj4sEl_LcYFCz-zU',
    appId: '1:785935802175:ios:7ee140a99f77a2119e3d8a',
    messagingSenderId: '785935802175',
    projectId: 'depi-ecommerce-9e1a8',
    storageBucket: 'depi-ecommerce-9e1a8.appspot.com',
    iosBundleId: 'com.example.simpleEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1ffeMe5kNhq_GdpF80IXvP5r5aiGBQRk',
    appId: '1:785935802175:web:1f64cfac6b4129429e3d8a',
    messagingSenderId: '785935802175',
    projectId: 'depi-ecommerce-9e1a8',
    authDomain: 'depi-ecommerce-9e1a8.firebaseapp.com',
    storageBucket: 'depi-ecommerce-9e1a8.appspot.com',
  );
}
